apiVersion: apps/v1
kind: Deployment
metadata:
  name: productapp-k8
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    
    matchLabels:
      app: productapp-k8
  template:
    metadata:
      labels:
        app: productapp-k8
    spec:
      containers:
      - name: productapp-k8
        image: sandy193/devops-app-springboot-ci-cd:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9080
